version: '3.8'
services:
  database:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  api:
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - database

volumes:
  db_data:
